# Generated by Django 5.0 on 2023-12-25 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.bet')),
            ],
        ),
        migrations.AddField(
            model_name='betparticipant',
            name='chosen_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.betoption'),
            preserve_default=False,
        ),
    ]
