# Generated by Django 5.0 on 2024-01-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bet_is_public_betoption_betparticipant_chosen_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betoption',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='betoption',
            unique_together={('bet', 'title')},
        ),
        migrations.AddConstraint(
            model_name='betoption',
            constraint=models.UniqueConstraint(fields=('bet', 'title'), name='unique_betoption_title'),
        ),
    ]
